apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guacamole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ACTLA/omgtu-gitops.git
    targetRevision: HEAD
    path: manifests/guacamole
  destination:
    server: https://kubernetes.default.svc
    namespace: guacamole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true